In [1]:
import pandas as pd

In [2]:
liste=[1,2,3,"a","b","c"]
liste

[1, 2, 3, 'a', 'b', 'c']

In [3]:
df=pd.DataFrame(liste,columns=["veri1"])
df

  veri1
0     1
1     2
2     3
3     a
4     b
5     c

In [5]:
import numpy as np

In [6]:
veriler=np.random.randint(1,100,([3,3]))
veriler

array([[47, 48, 97],
       [94, 20, 80],
       [14, 86, 23]])

In [8]:
#verileri dataframe olarak gösterin
df1=pd.DataFrame(veriler,index=["satır1","satır2","satır3"],columns=["sütun1","sütun2","sütun3"])
df1

        sütun1  sütun2  sütun3
satır1      47      48      97
satır2      94      20      80
satır3      14      86      23

In [10]:
veriler=[["Melisa","Tuğtekin",16],["İlayda","Daban",15]]
veriler

[['Melisa', 'Tuğtekin', 16], ['İlayda', 'Daban', 15]]

In [14]:
df2=pd.DataFrame(veriler,index=["ogrenci_1","ogrenci_2"],columns=["ad","soyad","yas"])
df2

               ad     soyad  yas
ogrenci_1  Melisa  Tuğtekin   16
ogrenci_2  İlayda     Daban   15

In [16]:
df2.info() #dataframe hakkında genel bilgi. Soru: veriler np olsaydı ne olurdu?

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, ogrenci_1 to ogrenci_2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ad      2 non-null      object
 1   soyad   2 non-null      object
 2   yas     2 non-null      int64
dtypes: int64(1), object(2)
memory usage: 64.0+ bytes